[package]
authors = ["Ferrous Systems"]
edition = "2021"
name = "xtask"
version = "0.0.0"

[dependencies]
color-eyre = "0.6"
ctrlc = "3.4"
hidapi = "2.4"
rusb = "0.9"
consts = { path = "../nrf52-code/consts" }
serialport = "4.2"
