[target.thumbv7em-none-eabihf]
# set custom cargo runner to flash & run on embedded target when we call `cargo run`
# for more information, check out https://github.com/probe-rs
runner = [
  "probe-rs",
  "run",
  "--chip=nRF52840_xxAA",
  "--allow-erase-all",
  "--log-format=oneline"
]

rustflags = [
  "-C", "link-arg=-Tlink.x", # use the cortex-m-rt linker script
  "-C", "linker=flip-link", # adds stack overflow protection
  "-C", "link-arg=-Tdefmt.x", # defmt support
]

[build]
# cross-compile to this target
target = "thumbv7em-none-eabihf" # = ARM Cortex-M4 with FPU

[env]
# DEFMT_LOG = "debug"
