manifest-version = 1

[products.ferrocene]
release = "stable-25.02.0"
packages = [
    "rustc-${rustc-host}",
    "rust-std-${rustc-host}",
    "cargo-${rustc-host}",
    "rustfmt-${rustc-host}",
    "rust-src",
    "rust-std-armv8r-none-eabihf",
]
